### ISSUE TITLE
Module doesnt update

### ISSUE THREAD

**Issue by lozanoje** [wyrmisis/zweihander-party-sidebar#2]
There is an error with manifest on updating:

![](https://i.ibb.co/6FTB3Td/2024-02-13-21-43-53.jpg)

**Comment by wyrmisis** [comment]
@lozanoje Hmm. I wonder if this is happening because this module hasn't had a proper Github release yet.

You might want to try `https://github.com/wyrmisis/zweihander-party-sidebar/releases/download/0.0.1-alpha2/module.json` instead of looking for the latest release. Let me know if that helps!
